<?php
/**
 * hook_schema() is used here.
 * for generating the schema for the table named student_feedback();
 */
function student_feedback_schema(): array {
  $schema['student_feedback'] = [
    'description' => 'Stores student feedback data.',
    'fields' => [
      'id' => [
        'type' => 'serial',
        'not null' => TRUE,
      ],
      'name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'email' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'message' => [
        'type' => 'text',
        'not null' => TRUE,
      ],
      'rating' => [
        'type' => 'int',
        'not null' => TRUE,
      ],
      'created' => [
        'type' => 'int',
        'not null' => TRUE,
      ],
    ],
    'primary key' => ['id'],
  ];

  return $schema;
}