<?php

use Drupal\Core\Form\FormStateInterface;

function user_details_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id === 'node_page_form') {
    $form['#validate'][] = 'user_details_page_form_validate';
  }
}
/**
 * Custom validation handler.
 */
function user_details_page_form_validate(&$form, FormStateInterface $form_state) {

  $title = $form_state->getValue('title')[0]['value'];

  if (strlen($title) < 5) {
    $form_state->setErrorByName('title', 'Title must be at least 5 characters long.');
  }
}